name: flutter_tmdb
description: Flutter demo project, using api from TMDb

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#0d253f"
  image: "images/ic_splash.png"
  android: true
  ios: true
  web: true
  android12: true



# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/

